name: Android CI (Testing)

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout el código
        uses: actions/checkout@v4

      - name: Configurar Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Gradle y Caché
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-overwrite-existing: true

      # Recreación de google-services.json usando decodificación binaria interna segura
      - name: Recrear google-services.json de manera segura
        uses: timheuer/create-content-file@v7
        with:
          fileName: 'app/google-services.json'
          content: ${{ secrets.GOOGLE_SERVICES_JSON }}
          isBase64: true

      - name: Dar permisos de ejecución a Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Ejecutar Pruebas Unitarias (Local)
        run: ./gradlew testDebugUnitTest --continue

      - name: Subir Reportes de Test
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: app/build/reports/tests/testDebugUnitTest/